version: '3.9'

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: blackoffer
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
    
volumes:
  postgres_data: